"""crear tablas rbac

Revision ID: f296f995be77
Revises: 
Create Date: 2026-09-25 03:43:34.810409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f296f995be77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicativos',
    sa.Column('aplicativo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compania_id', sa.Integer(), nullable=False),
    sa.Column('nom_aplicativo', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('aplicativo_id')
    )
    op.create_table('cargo',
    sa.Column('cargo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compania_id', sa.Integer(), nullable=False),
    sa.Column('nombre_cargo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cargo_id')
    )
    op.create_table('permisos',
    sa.Column('permiso_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permiso', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('permiso_id')
    )
    op.create_table('roles',
    sa.Column('rol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aplicativo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['aplicativo_id'], ['aplicativos.aplicativo_id'], ),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('cargo_roles',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.cargo_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.rol_id'], ),
    sa.PrimaryKeyConstraint('cargo_id', 'rol_id')
    )
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.permiso_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.rol_id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_permisos')
    op.drop_table('cargo_roles')
    op.drop_table('roles')
    op.drop_table('permisos')
    op.drop_table('cargo')
    op.drop_table('aplicativos')
    # ### end Alembic commands ###
